global using Basket.API.Models;
global using BuildingBlocks.CQRS;
global using Carter;
global using MediatR;
global using Mapster;
global using FluentValidation;
global using Basket.API.Exceptions;
global using Marten;
global using BuildingBlocks.Exceptions;